### ISSUE TITLE
Website text size got small sitewide

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#1722]
**Bug Description**
All the body text size in our website looks small, can we revert it back to what it use to be?

**Steps to Reproduce**
thenewboston.com

**Expected behavior**
Body font was 16px and 14px in leaderboard

**Actual behavior**
Everything looks either 14px or 12px. 

**OS and Browser**
chrome

**Comment by jamessspanggg** [comment]
@thesanjeevsharma @angle943  did some investigation here 😟:

When inspecting through chrome, the `:root` style seems to not match with the global `_font.scss` values, since mostly our fonts utilises `--font-size-regular`, it became 14px instead of 16px:
<img width="351" alt="Screen Shot 2021-04-17 at 6 00 19 PM" src="https://user-images.githubusercontent.com/32864116/115109212-00ff0580-9fa7-11eb-8b70-00b47219111b.png">

<img width="352" alt="Screen Shot 2021-04-17 at 5 44 26 PM" src="https://user-images.githubusercontent.com/32864116/115109233-1411d580-9fa7-11eb-86d7-f1af97f3c68e.png">

**Comment by jamessspanggg** [comment]
ah realised what was the issue, it was because `@thenewboston/ui` package contains a `font.css` file which also sets the `:root` css for fonts. I believe what happen was the `_font.scss` file was loaded and parsed first before the `font.css` of `@thenewboston/ui`, which caused the latter to have a higher specificity 😧 

<img width="1518" alt="Screen Shot 2021-04-17 at 8 02 37 PM" src="https://user-images.githubusercontent.com/32864116/115112385-dcf7f000-9fb7-11eb-9c8f-51d90d575dd5.png">

**Comment by jamessspanggg** [comment]
Created a temporary solution which is to standardise the `:root` css in the `@thenewboston/ui` repo. However, this might not be the best solution as when one side changes, we will need to standardise with the other to prevent conflict. 

A better solution may be just to make the `@thenewboston/ui` css local to itself.

**Comment by jamessspanggg** [comment]
@angle943 can you take a look at this issue? it may affect the App wide UI update
