### ISSUE TITLE
Blog: Text color in Dark Mode

### ISSUE THREAD

**Issue by Lalisfeed** [thenewboston-developers/Website#1942]
**Bug Description**
Darkmode : text color doesn't look right

**Steps to Reproduce**
1. Go to 'https://blog.thenewboston.com/2021/07/08/building-the-fastest-blockchain/'
2. Scroll down to 'Table of Contents'
3. See error

**Expected behavior**
Bright colored text

**Actual behavior**
Unchanged color

**Screenshots/Recordings**
<img src="https://user-images.githubusercontent.com/59479762/125375487-bd9a1480-e3a6-11eb-98f8-679604f4331e.jpg" width="300px" />

**OS and Browser**
 - OS: Android
 - Browser: Chrome

**Additional context**
The external comment form too has similar issue
<img src="https://user-images.githubusercontent.com/59479762/125375800-503ab380-e3a7-11eb-90f6-2c9957932a95.jpg" width="250px" />

**Comment by jamessspanggg** [comment]
@manishram who is in charge of the blog? do we have a separate repo for the blog?

**Comment by manishram** [comment]
Hey, @jamessspanggg we are using WordPress for the blog. We don't have any repo for that. 

Regarding this issue,
1st Issue: Table of Contents is SOLVED
2nd issue: The issue is arising from the WordPress theme. We already reported this to the respective WordPress theme developer.

This issue can be closed I think.

**Comment by Lalisfeed** [comment]
It's ok then I'll close it
