### ISSUE TITLE
[FAQ] Remove the # coming when hovered on questions 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#373]
Url : https://thenewboston.com/faq
![image](https://user-images.githubusercontent.com/59204822/97836792-0d4a1b80-1d03-11eb-9cb0-2ce6c6c7a226.png)

**Comment by itsnikhil** [comment]
Are you sure about removing that... I think it is there for a purpose

**Comment by webdeveloperswj** [comment]
When clicked on it remains on same page so

**Comment by itsnikhil** [comment]
Yes, it is a common practice to have this kind of functionality to jump between sections within the same page. For example: If you want to share specific question you can use that #link so that page will open to that section with that question. That being said, jump links are good for long pages but FAQ isn't that long.
Please consult with design team first and I will be happy to resolve the issue whatever will be the final call.

**Comment by buckyroberts** [comment]
We can keep them. The FAQ section will soon be much longer and we want to be able to link people to specific questions.
