### ISSUE TITLE
Design Assets page

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#523]
place for people to download our logo

**Comment by manishram** [comment]
Hey @kristykjlee , I want to work on it. Can you explain a bit more? I mean just thenewboston logos of different resolutions or something else?

**Comment by kristykjlee** [comment]
> Hey @kristykjlee , I want to work on it. Can you explain a bit more? I mean just thenewboston logos of different resolutions or something else?

You got it, so like you said, we just need a place for people to download our logo. Similar to how ethereum has a place where you can download their logos. https://ethereum.org/en/assets/ 
Here are the different logo sizes we've got. I'm going to assign you to this ticket. 

[thenewboston logos.zip](https://github.com/thenewboston-developers/Website/files/5505472/thenewboston.logos.zip)

**Comment by Nevah422** [comment]
I am new here, I have an idea and an easy solution for our logo download. I would like to help with this project.

**Comment by mulilo** [comment]
hi im really new.
we just need a place for people to download our logo.

like a server or github page ?

thanks mulilo

**Comment by Nevah422** [comment]
I use mediafire.com they give you 1TB free to download content. The best part is every file you download gets its own link address. You can make it private or public, so once you create a link you would just that and be downloaded by whoever has link. I can create a link if neededThank you,AmySent from my Samsung Galaxy smartphone.
-------- Original message --------From: mulilo <notifications@github.com> Date: 11/8/20  6:12 AM  (GMT-05:00) To: thenewboston-developers/Website <Website@noreply.github.com> Cc: Nevah422 <burcham.amy1@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [thenewboston-developers/Website] Design Assets page (#523) 
hi im really new.
we just need a place for people to download our logo.
like a server or github page ?
thanks mulilo

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/thenewboston-developers/Website/issues/523#issuecomment-723562216",
"url": "https://github.com/thenewboston-developers/Website/issues/523#issuecomment-723562216",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mulilo** [comment]
Thank you will follow it up.

Mulilo

**Comment by manishram** [comment]
@kristykjlee Let me know If the design is good enough?
![assetspage](https://user-images.githubusercontent.com/22790904/98484032-be384500-2232-11eb-9ea6-ff88c3a12ad9.png)
