### ISSUE TITLE
Task Left Menu Issue

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#564]
@kristykjlee we have a new repo that we want to include on the Tasks page on the website, however the name of the repo is `thenewboston-python-client` which is a bit long. 

<img width="856" alt="Screen Shot 2020-11-06 at 4 13 22 PM" src="https://user-images.githubusercontent.com/8547538/98425739-1f9dbf80-204b-11eb-9280-3087260d6d5b.png">

**Comment by manishram** [comment]
Why not just replace thenewboston with TNB and write it like TNB-python-client?

![gregeg](https://user-images.githubusercontent.com/22790904/98432950-ffbcd900-20e8-11eb-995d-9939d4e1d02f.JPG)

**Comment by mofodox** [comment]
And maybe the naming convention should be ‘TNB-Python’ and ‘TNB-Python-Client’?

**Comment by myszon01** [comment]
what projects thenewboston-python-client and thenewboston-python are mainly responsible for?

**Comment by stainlezzking** [comment]
since you already have a "thenewboston-python" that you're okay with, it's only symmetrical to name the other one "thenewboston-python-C" but if you're okay with changing both names, then I'll go with the idea of the guy above me  'TNB-python-client

**Comment by Akash-S1999** [comment]
I would recommend changing "thenewboston" to TNB. Like "TNB-python", "TNB-python-Client" In that way, it will look more appealing and simple.  Also, we can skip the word python and include it in the documentation part. 
The latter idea is better as we can have a menu "TNB-python" and the subpart can be "TNB-python-client" or just "TNB-Client" as it will already be the subpart of "TNB-Python"

**Comment by JanGoO-dev** [comment]
I think this will be a better solution, If you don't want to change your repository name.
Bellow Image is a basic demonstration of the solution. I mean you should give a common title to both of these two repositories and make it unclickable while bellow that you should have two small buttons for each of the repositories.

Example:
thenewboston
--python
--python-client

I hope you understand. English is not my native language that's why there might be some mistakes.

![Screenshot-2020-11-07-194401](https://user-images.githubusercontent.com/55313789/98444715-05401080-2135-11eb-8e02-d13e0c5210d1.png)

I am a big fan and student of your. I learned CPP by watching your videos and know I am studding computer science. You inspired me and your work always motivates me. Thank you for everything.

**Comment by Ayush-Porwal** [comment]
@buckyroberts can I take this? I think this is easy and it would be a nice start for me. Thank you!

**Comment by kristykjlee** [comment]
> Why not just replace thenewboston with TNB and write it like TNB-python-client?
> 
> ![gregeg](https://user-images.githubusercontent.com/22790904/98432950-ffbcd900-20e8-11eb-995d-9939d4e1d02f.JPG)

I like this idea, can someone implement this?

**Comment by manishram** [comment]
Hey, @kristykjlee I want to work on it.  :)

**Comment by kristykjlee** [comment]
> Hey, @kristykjlee I want to work on it. :)

All yours!

**Comment by KarenEfereyan** [comment]
It really is @buckyroberts you were my programming hero. I learnt java from you. I still have your videos

**Comment by manishram** [comment]
@thesanjeevsharma can you please review this
