### ISSUE TITLE
Error 404 when refreshing any page (except the home page)

### ISSUE THREAD

**Issue by Hristijan95** [thenewboston-developers/Website#595]
**Bug Description**
If you navigate to any page (and reload the page), except for the home page, and monitor the Network activity in inspect element, you will notice that there is an error 404, however the actual page is loaded. I am not sure why is this happening, but it causes on some browsers to show that the page is down, for example if you use Brave, you get the top bar which says "Sorry, that page is missing". You can see the behavior in the screenshot below:
<img width="1440" alt="Screen Shot 2020-11-07 at 18 41 30" src="https://user-images.githubusercontent.com/5727677/98447979-4e8a6300-2129-11eb-94bc-9f25ce5139b9.png">

**Steps to Reproduce**
1. Go to https://thenewboston.com/faq or any other page (except for the home page)
2. Open the developer tools on your browser and navigate to the network tab
3. Reload the page and look at the network requests and you'll notice the 404 error

**Expected behavior**
It's self explanatory. 

**OS and Browser**
 - Brave browser (macos)
 - Safari (macos)
 - And probably on any other broser

**Account Number**
1002530d2ef3da6207c5a5070d427984a8508a715ce18afb07f394aa47d73751

**Comment by BakungaBronson** [comment]
Could it be what is keeping the tasks page behind as well or do you think that is a separate issue?

**Comment by Hristijan95** [comment]
@BakungaBronson I don't know how are the GitHub issues fetched(I will take the time to see that later), but I think that's a separate issue, I don't see a connection between those.

**Comment by BakungaBronson** [comment]
Sorry about that then. I will create a new issue on that

**Comment by thesanjeevsharma** [comment]
@Hristijan95 You wanna take this issue?

**Comment by Hristijan95** [comment]
@thesanjeevsharma Sure, I'm taking it.

**Comment by Hristijan95** [comment]
Okay, so I tested the scenario locally and it can't be reproduced, so I took a guess that the issue is not with the react app, but with the server configuration and I think that's the case. The solution and reason for this happening is explained in [this stackoverflow answer](https://stackoverflow.com/a/43557288).

Basically, it's a small configuration change in the nginx server (I hope that we use nginx, if not, it should be the same case for any other server). The idea is when nginx cannot find anything on the route that we are requesting, for example /faq it throws 404, so we need to tell nginx that instead of throwing 404, it should redirect to the index.html file and the routing will be handled by react there.

**Comment by thesanjeevsharma** [comment]
@Hristijan95  Thank you for looking into it.

@buckyroberts Please have a look at this.

**Comment by hinduBale** [comment]
Well, I don't know whether this would be helpful or not, but in one of my personal React projects, I had the same problem. Every time I refreshed a page apart from the Home Page, the server threw a 404 error. 
As one might suspect, I was not using the *exact* keyword in the *Route* parameter
`const App = () => {
    return(
        <BrowserRouter>
            <Route path = "/" exact component = {Join} />
            <Route path = "/chat"  component = {Chat} />
        </BrowserRouter>
    );
};
`
But still, I was getting a 404 after refreshing anything other than the Home-Page. So, I decided to switch between client side and server side handling of routes and switched to `HashRouter` instead of the `BrowserRouter` and everything just worked fine then onwards. I guess, that it could be worth a try.

**Comment by stage88** [comment]
Hey all, sorry to jump in...

I can see you guys are using AWS CloudFront to host your site, backed by an S3 origin. I've maintained a few sites using AWS CF+S3, this is a common issue and it can be fixed by updating the CF configuration in AWS.

What happens here is that a request at the origin for (lets say) https://thenewboston.com/guide/introduction is a 404 because that page doesn't exist in the S3 bucket.

I am guessing you have a custom mapping for HTTP 404 in the CF distribution that responds with '/index.html', you just have to map that response into HTTP 200.

Here is an example, hope I am on the right path and this help you resolve your issue.

![image](https://user-images.githubusercontent.com/9906800/98665964-7a634e00-23a0-11eb-9f9d-9e35de201946.png)

**Comment by Hristijan95** [comment]
@buckyroberts , can you please take a look at this when you have the time?

**Comment by buckyroberts** [comment]
Assigned it to @shashanksinha89 - he is out today but can work on it when he gets back.

**Comment by shashanksinha89** [comment]
@Hristijan95 enabled custom error response for now as this seems to be a race condition.

![image](https://user-images.githubusercontent.com/13620565/102362165-8066d300-3fcd-11eb-9296-e5d3b013898d.png)


Also this is worth checking, if this fixes **404** then we don't need custom error response on CF - [how-to-avoid-404-error-when-reload-a-page-in-react](https://stackoverflow.com/questions/55380091/how-to-avoid-404-error-when-reload-a-page-in-react/55380380)

<img width="735" alt="Screen Shot 2020-12-16 at 6 28 06 PM" src="https://user-images.githubusercontent.com/13620565/102361248-74c6dc80-3fcc-11eb-8603-0f931cdfe5d3.png">

**Comment by Rajputusman** [comment]
@shashanksinha89 Can I get your **TNB Account Number**, So I can send you your **PR-reward**?
