### ISSUE TITLE
[Documentation] Code segments under CSS / SASS not highlighted properly

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#733]
**Bug Description**
The code segments within the CSS / SASS section are not highlighted properly, especially  `jsx` code segments.

**Steps to Reproduce**
1. Go to Documentation -> CSS /SASS
2. Scroll to [Block Elements](https://thenewboston.com/style-guide/css#blocks-elements)
3. View that the jsx code segments are not highlighted properly

**Expected behavior**
The JSX code should be highlighted properly.

**Actual behavior**
The JSX code not highlighted properly, some parts are white in colour.

**Screenshots/Recordings**
<img width="752" alt="Screen Shot 2020-11-11 at 9 39 27 PM" src="https://user-images.githubusercontent.com/32864116/98821858-0b9ef700-246b-11eb-9dd7-32219af75af1.png">

**OS and Browser**
 - OS: Mac, Chrome

**Additional context**
May be due to not up-to-date `react-syntax-highlighter` package.

**Account Number**
c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by lapstjup** [comment]
@jamessspanggg  - Thanks for raising this issue. I checked your PR but there are inconsistency around what get's highlighted and what doesn't in other blocks. Sometimes they are all white instead of the lightgreen tinge in others. If you can make them all look aesthetically the same, that would be great.
