### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by IronManCool001** [thenewboston-developers/Website#783]
Hey guys this is actually a suggestion to turn your website into a **PWA** so it will be actually be installable on the phone as **PWA** are meant to be installable and faster

**Comment by ddyakov** [comment]
I think they already designed a mobile application and it will probably move into the implementation process (maybe already is), so I don't know how useful that would be.

**Comment by manishram** [comment]
Currently website does not contain anything where users can interact more. Neither the website's performance can be improved with the use of PWA because currently it only contains data and documentations. So right now there is no need of PWA. Users can add to their home screen if they really want to. Once the website have some interacting features, there will be reason to have PWA.

**Comment by kandarpgautam** [comment]
Actually, native mobile applications are heavy. Progressive web application is really a good idea as it's light and will take storage space in KBs on user's device. Size matters a lot.

**Comment by Hristijan95** [comment]
I don't think we'll ever need to have this website as a mobile application.
Maybe there'll be mobile apps for things such as the planned marketplace, but that will be a separate thing.
