### ISSUE TITLE
Download page fetches all releases

### ISSUE THREAD

**Issue by ffpetrovic** [thenewboston-developers/Website#849]
**Bug Description**
The download page fetches all releases, whereas we only care about the latest one. At least on this page.

**Steps to Reproduce**
1. Go to [https://thenewboston.com/download](https://thenewboston.com/download)
2. Look at the network request to `/releases`

**Expected behavior**
Only the latest release should be fetched. The solution right now seems to be to use pagination.

**Actual behavior**
All releases are fetched.

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/5026566/99198899-cdbc0e80-279b-11eb-92e1-73f2751867b3.png)

**OS and Browser**
All

**Additional context**

**Account Number**
Your account number where the reward coins for this bug bounty will be sent (pending review and approval).

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by thesanjeevsharma** [comment]
@Hristijan95 @lapstjup I think this was done so that users can choose from various versions(at a later point in time). The UI doesn't support that yet, tho. 

What do you think?

**Comment by lapstjup** [comment]
@thesanjeevsharma Not sure about the fetching all versions part but if it's not that then I think the current is a pre-release and not a production ready release and that's why developers have the logic for fetching all releases and then getting the latest one.

@ffpetrovic Your solution will work but I think once we hit the release mode, we can just utilise https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-the-latest-release endpoint to fetch latest release - it doesn't work for pre-releases.

**Comment by ffpetrovic** [comment]
@lapstjup Then this can be refactored to use that before the first production-ready release.
